name: 2.3.1 Протокол и API

on:
  push:
    paths:
      - '231-firmware-template/**'
      - 'libs/**'
      - '.github/workflows/check-2-3-1.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ant-lab-ru/es-test/.github/workflows/check-2-3-1.yml@master
    secrets:
      ES_ACCOUNT_SECRET: ${{ secrets.ES_ACCOUNT_SECRET }}
