name: 2.2.3 Цена вычислений

on:
  push:
    paths:
      - '221-command-time/**'
      - '.github/workflows/check-2-2-3.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ant-lab-ru/es-test/.github/workflows/check-2-2-3.yml@master
    secrets:
      ES_ACCOUNT_SECRET: ${{ secrets.ES_ACCOUNT_SECRET }}
