name: 2.3.9 Изменение требований

on:
  push:
    paths:
      - '239-two-buttons/**'
      - 'libs/**'
      - '231-firmware-template/**'
      - '.github/workflows/check-2-3-9.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ant-lab-ru/es-test/.github/workflows/check-2-3-9.yml@master
    secrets:
      ES_ACCOUNT_SECRET: ${{ secrets.ES_ACCOUNT_SECRET }}
